# Generated by Django 3.0 on 2019-12-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='liked',
            field=models.IntegerField(default=0),
        ),
    ]
