# Generated by Django 3.0 on 2019-12-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_complaint_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='solved',
        ),
    ]
