# Generated by Django 3.0 on 2019-12-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_auto_20191225_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='level',
            field=models.CharField(default='Department Level', max_length=20),
        ),
    ]
