# Generated by Django 3.0.1 on 2019-12-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0008_auto_20191228_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='url',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
