# Generated by Django 3.0 on 2019-12-27 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.CharField(default='', max_length=100)),
                ('teacher_id', models.CharField(default='', max_length=100)),
                ('college', models.CharField(default='', max_length=100)),
                ('is_approved', models.BooleanField(default='False')),
                ('phone_no', models.CharField(default='', max_length=10)),
                ('pending_request', models.CharField(default='', max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
