# Generated by Django 2.2.5 on 2020-01-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_admin', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='dob',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
