# Generated by Django 2.2.5 on 2020-01-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_admin', '0003_auto_20200112_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='branch',
            field=models.CharField(default='', max_length=30),
        ),
    ]
