# Generated by Django 2.2.5 on 2020-01-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_admin', '0004_committeemember_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='address',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
