# Generated by Django 2.2.5 on 2019-12-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=20)),
                ('college_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
            ],
        ),
    ]
