# Generated by Django 3.0 on 2019-12-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_student', '0002_auto_20191224_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='liked_complaint',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
