# Generated by Django 3.0.1 on 2019-12-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_student', '0005_student_post_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='profile_picture'),
            preserve_default=False,
        ),
    ]
