# Generated by Django 3.0.1 on 2019-12-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_student', '0007_auto_20191228_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(default=0, upload_to='profile_picture/'),
        ),
    ]
