# Generated by Django 3.0.1 on 2019-12-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_student', '0008_auto_20191228_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_picture',
        ),
    ]
