# Generated by Django 3.0.1 on 2019-12-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_student', '0009_remove_student_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(default='media/profile_pictue/IMG_1520.JPG', upload_to='profile_picture/'),
        ),
    ]
