# Generated by Django 2.2.5 on 2020-01-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_student', '0011_auto_20191228_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(default='profile_picture/IMG_1520.JPG', upload_to='profile_picture/'),
        ),
    ]
