# Generated by Django 2.2.5 on 2020-01-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_student', '0012_auto_20200111_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='', max_length=100),
        ),
    ]
